---
version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    volumes:
      - /home/manoelbenedito/Documentos/faculdade/tcc/tmp/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "Admin1234" #user postgres

  postgres-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 15080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "manoelneto164@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin1234"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    depends_on:
      - kafka
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://connect:8083
      PORT: 9021

  connect:
    image: confluentinc/cp-kafka-connect:7.1.1
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8083:8083
    environment:
        LOG_LEVEL: DEBUG
        CONNECT_BOOTSTRAP_SERVERS: kafka:9092
        CONNECT_GROUP_ID: pg-sink
        CONNECT_CONFIG_STORAGE_TOPIC: __pg.sink.config.storage
        CONNECT_STATUS_STORAGE_TOPIC: __pg.sink.status.storage
        CONNECT_OFFSET_STORAGE_TOPIC: __pg.sink.offset.storage
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_REST_PORT: 8083
        CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
        CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181