---
version: '3'
services:
  postgres-server:
    image: postgres:latest
    restart: on-failure
    ports:
      - 15432:5432
    expose:
      - "5432"
    volumes:
      - ${PG_LOCAL_VOLUME}:/var/lib/postgresql/data
      - ./config/postgres.conf:/var/lib/postgresql/data/postgresql.auto.conf
    env_file:
      - ./config/postgres.env
    networks:
      - kafka-project

  postgres-admin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    depends_on:
      - postgres-server
    ports:
      - 15080:80
    env_file:
      - ./config/pgadmin.env
    networks:
      - kafka-project

  app:
    build: .
    restart: on-failure
    depends_on:
      - postgres-server
    env_file:
      - ./config/data-app.env
    entrypoint: python3 -u app.py
    networks:
      - kafka-project

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    env_file:
      - ./config/zookeeper.env
    networks:
      - kafka-project

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    depends_on:
      - zookeeper
      - postgres-server
    ports:
      - 9092:9092
      - 9094:9094
    env_file:
      - ./config/kafka.env
    networks:
      - kafka-project
  
  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.1.1
    restart: on-failure
    depends_on:
      - zookeeper
      - kafka
      - postgres-server
    ports:
      - 8083:8083
    env_file:
      - ./config/kafka-connect.env
    command:
      - bash
      - -c
      - |
        echo "Installing Connector"
        confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.5.0
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        #
        sleep infinity
    networks:
      - kafka-project

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    restart: on-failure
    depends_on:
      - zookeeper
      - kafka
      - kafka-connect
    ports:
      - 9021:9021
    env_file:
      - ./config/control-center.env
    networks:
      - kafka-project

networks:
  kafka-project:
    driver: bridge